# netlify.toml
[build]
  publish = "build"  # This tells Netlify to serve files from the 'build' folder (created with npm run build)
  command = "npm run build"  # Command to build the project

[[redirects]]
  from = "/*"  # Redirect all routes
  to = "/index.html"  # Serve index.html
  status = 200
